import os
import sales_analyzer as sa
# I'm using a random .csv file generated by AI for sales data of sweets. 

def main():
    data_file = 'kanti_sweets_sales_dirty.csv'
        
    # Process Data
    print("Loading and cleaning data...")
    raw_df = sa.load_and_clean_data(data_file)
    processed_df = sa.feature_engineering(raw_df)
    print("Data processed and cleaned successfully!\n")
    
    # CLI Interactive Menu
    while True:
        print("\n" + "=" * 40)
        print("   KANTI SWEETS SALES ANALYZER")
        print("=" * 40)
        print("1. View Best-Selling Sweet")
        print("2. View Branch Profits")
        print("3. View Busiest Season")
        print("4. View All Analytics Graphs")
        print("5. Exit")
        
        choice = input("\nEnter your choice (1-5): ").strip()
        
        if choice == '1':
            sweet, qty = sa.get_best_seller(processed_df)
            print(f"\n[RESULT] The best-selling sweet is '{sweet}' with {qty:,.2f} kg sold.")
        
        elif choice == '2':
            profits = sa.get_branch_profits(processed_df)
            print("\n[RESULT] Branch Profits:")
            print(profits.to_string(index=False))
            
        elif choice == '3':
            season, rev = sa.get_busiest_season(processed_df)
            print(f"\n[RESULT] The busiest season is '{season}' generating ₹{rev:,.2f} in gross revenue.")
            
        elif choice == '4':
            print("\n[RESULT] Generating graphs... Check the new popup windows.")
            # Note: The program will pause until you close the graph windows
            sa.plot_branch_profits(processed_df)
            sa.plot_sweet_sales(processed_df)
            
        elif choice == '5':
            print("\nExiting the analyzer. Have a sweet day!")
            break
            
        else:
            print("\nInvalid input. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main()